### Listar
GET {{API_HOST}}/invoices?distributor=CMIG&year=2024&clientId=7204076116

### Cadastrar
POST {{API_HOST}}/invoices
Content-Type: application/json

{
  "personal": {
    "name": "JOSE MESALY FONSECA DE CARVALHO 52024156",
    "clientId": "7204076116",
    "meterId": "3001116735"
  },
  "general": {
    "date": "MAR/2022",
    "due": "02/04/2022",
    "payment": 109.48,
    "distributor": "CEMIG"
  },
  "electricalEnergy": {
    "quantity": 50,
    "priceUnit": 0.95863974,
    "value": 47.92,
    "tax": 0.74906
  },
  "scee": {
    "quantity": 504,
    "priceUnit": 0.51141778,
    "value": 257.74,
    "tax": 0.48733
  },
  "compensatedEnergy": {
    "quantity": 504,
    "priceUnit": 0.48733,
    "value": -245.61,
    "tax": 0.48733
  },
  "publicEnergy": {
    "value": 49.43
  },
  "total": {
    "value": 109.48
  }
}
### Dashboard
GET {{API_HOST}}/dashboard
